### ISSUE TITLE
PHP7 Update

### ISSUE THREAD

**Issue by checkerschaf** [Scout24/restapi-php-sdk#47]
Hey,

I'd recommend an update to PHP7 for maximum compatibility. Currently it's not working with many current releases of the most used frameworks.

Thanks!

**Comment by all4pages** [comment]
Yes with PHP7 no 3legged-oAuth

**Comment by all4pages** [comment]
I only git REQUEST and not APPLICATION in the Database whe I tried to autentify the aplication.
I found a error in the file: Imocaster/Data/Mysql.php
In the function: saveApplicationToken()
-304: 'APPLICATION','".$sToken."','".$sSecret."','0000-00-00 00:00:00.000000','".$sUser."'
+304: 'APPLICATION','".$sToken."','".$sSecret."','1000-01-01 00:00:00.000000','".$sUser."'

The range from Datetime is 1000-01-01 00:00:00.000000 to 9999-12-31 23:59:59.999999
So the mysqli_query will never return true and so the script:  Imocaster/Data/Rest.php
with the funktion: registerAccess()
will always fall back to function: registerRequest()
and so you never get the application autentified.

I go on :-)

**Comment by christianbarkowsky** [comment]
Tested positive. Please fix the bug. 🙏
